# Generated by Django 4.1 on 2022-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
